# Generated by Django 5.0.2 on 2025-06-19 22:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alertas",
            fields=[
                (
                    "alerta_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_alerta",
                    models.CharField(
                        choices=[
                            ("ST", "Stock bajo"),
                            ("EX", "Producto expirado"),
                            ("OT", "Otro"),
                        ],
                        max_length=10,
                    ),
                ),
                ("mensaje", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PN", "Pendiente"),
                            ("R", "Resuelta"),
                            ("CN", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de inventario",
                "verbose_name_plural": "Alertas de inventario",
                "db_table": "Alertas",
            },
        ),
        migrations.CreateModel(
            name="Categorias",
            fields=[
                (
                    "categoria_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="MovimientosInventario",
            fields=[
                (
                    "movimiento_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[("in", "Entrada"), ("EX", "Salida"), ("ST", "Ajuste")],
                        max_length=7,
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Movimiento de inventario",
                "verbose_name_plural": "Movimientos de inventario",
                "db_table": "MovimientosInventario",
            },
        ),
        migrations.CreateModel(
            name="Productos",
            fields=[
                (
                    "producto_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                (
                    "codigo_barras",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "Productos",
            },
        ),
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "unidad_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("simbolo", models.CharField(blank=True, max_length=10, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Unidad de Medida",
                "verbose_name_plural": "Unidades de Medida",
                "db_table": "UnidadMedida",
            },
        ),
    ]
