# Generated by Django 5.2 on 2025-04-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="negocio_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.negocio"
            ),
        ),
        migrations.AddField(
            model_name="compras",
            name="negocio_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.negocio"
            ),
        ),
        migrations.AddField(
            model_name="detallecompra",
            name="compra_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.compras"
            ),
        ),
        migrations.AddField(
            model_name="detallecompra",
            name="negocio_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.negocio"
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="negocio_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.negocio"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="categorita",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.categoria"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="negocio_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.negocio"
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.producto"
            ),
        ),
        migrations.AddField(
            model_name="detallecompra",
            name="producto_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.producto"
            ),
        ),
        migrations.AddField(
            model_name="proveedores",
            name="negocio_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.negocio"
            ),
        ),
        migrations.AddField(
            model_name="compras",
            name="proveedor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.proveedores"
            ),
        ),
        migrations.AddField(
            model_name="unidadmedida",
            name="negocio_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.negocio"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="unidad_medida",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventario.unidadmedida",
            ),
        ),
    ]
