# Generated by Django 5.0.2 on 2025-06-19 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertas",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.negocios"
            ),
        ),
        migrations.AddField(
            model_name="categorias",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.negocios"
            ),
        ),
        migrations.AddField(
            model_name="movimientosinventario",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.negocios"
            ),
        ),
        migrations.AddField(
            model_name="productos",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventario.categorias",
            ),
        ),
        migrations.AddField(
            model_name="productos",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.negocios"
            ),
        ),
        migrations.AddField(
            model_name="movimientosinventario",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.productos"
            ),
        ),
        migrations.AddField(
            model_name="unidadmedida",
            name="negocio",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="usuarios.negocios",
            ),
        ),
        migrations.AddField(
            model_name="productos",
            name="unidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventario.unidadmedida",
            ),
        ),
    ]
