# Generated by Django 5.0.2 on 2025-06-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productos",
            name="fecha_expiracion",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
