# Generated by Django 5.0.2 on 2025-06-14 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_productos_fecha_expiracion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productos",
            name="unidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventario.unidadmedida",
            ),
        ),
    ]
