# Generated by Django 5.0.2 on 2025-06-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productos",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Foto del producto"
            ),
        ),
    ]
