# Generated by Django 5.0.2 on 2025-06-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_alter_productos_unidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadmedida",
            name="simbolo",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
