# Generated by Django 5.0.2 on 2025-06-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_productos_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productos",
            name="foto",
        ),
    ]
