# Generated by Django 5.0.2 on 2025-06-07 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        ("usuarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "cliente_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "dni",
                    models.CharField(max_length=8, unique=True, verbose_name="DNI"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Teléfono"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "negocio",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.negocios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "Clientes",
                "ordering": ["fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Descuentos",
            fields=[
                (
                    "descuento_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Descuento"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción del Descuento"
                    ),
                ),
                (
                    "tipo_descuento",
                    models.CharField(
                        choices=[("PR", "Porcentaje"), ("M", "Monto Fijo")],
                        default="PR",
                        max_length=20,
                        verbose_name="Tipo de Descuento",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto de descuento",
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Porcentaje de descuento",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de fin"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventas.clientes",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.negocios",
                    ),
                ),
                (
                    "productos",
                    models.ManyToManyField(
                        blank=True,
                        to="inventario.productos",
                        verbose_name="Productos Aplicables",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descuento de venta",
                "verbose_name_plural": "Descuentos de ventas",
                "db_table": "Descuentos",
                "ordering": ["descuento_id"],
            },
        ),
        migrations.CreateModel(
            name="Ventas",
            fields=[
                (
                    "venta_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total"
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[("EF", "Efectivo"), ("TR", "Tarjeta")],
                        max_length=10,
                        verbose_name="Método de Pago",
                    ),
                ),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[("PD", "Pendiente"), ("CT", "Completado")],
                        max_length=10,
                        verbose_name="Estado de pago",
                    ),
                ),
                (
                    "estado_envio",
                    models.CharField(
                        choices=[
                            ("PT", "Pendiente"),
                            ("EV", "En envio"),
                            ("ET", "Entregado"),
                        ],
                        max_length=10,
                        verbose_name="Estado de envío",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventas.clientes",
                    ),
                ),
                (
                    "descuento",
                    models.ManyToManyField(
                        blank=True,
                        to="ventas.descuentos",
                        verbose_name="Descuento aplicado",
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.negocios",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "db_table": "Ventas",
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="DetalleVentas",
            fields=[
                (
                    "detalle_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(editable=False)),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.productos",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventas.ventas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Venta",
                "verbose_name_plural": "Detalles de Ventas",
                "db_table": "DetalleVentas",
                "ordering": ["detalle_id"],
            },
        ),
    ]
