# Generated by Django 5.2 on 2025-04-21 14:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        ("usuarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "cliente_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("dni", models.CharField(max_length=8, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "negocio_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.negocio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Descuentos",
            fields=[
                (
                    "descuento_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("tipo_descuento", models.CharField(max_length=50)),
                ("porcentaje", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "cliente_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventas.clientes",
                    ),
                ),
                (
                    "negocio_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.negocio",
                    ),
                ),
                (
                    "producto_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ventas",
            fields=[
                (
                    "venta_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("metodo_pago", models.CharField(max_length=50)),
                ("estado", models.CharField(max_length=50)),
                ("tipo_venta", models.CharField(max_length=50)),
                (
                    "cliente_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventas.clientes",
                    ),
                ),
                (
                    "negocio_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.negocio",
                    ),
                ),
                (
                    "usuario_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                (
                    "detalle_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "producto_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.producto",
                    ),
                ),
                (
                    "venta_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ventas.ventas"
                    ),
                ),
            ],
        ),
    ]
