# Generated by Django 5.0.2 on 2025-06-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventas",
            name="estado_envio",
            field=models.CharField(
                blank=True,
                choices=[("PT", "Pendiente"), ("EV", "En envio"), ("ET", "Entregado")],
                default="ET",
                max_length=10,
                null=True,
                verbose_name="Estado de envío",
            ),
        ),
        migrations.AlterField(
            model_name="ventas",
            name="estado_pago",
            field=models.CharField(
                blank=True,
                choices=[("PD", "Pendiente"), ("CT", "Completado")],
                default="CT",
                max_length=10,
                null=True,
                verbose_name="Estado de pago",
            ),
        ),
        migrations.AlterField(
            model_name="ventas",
            name="metodo_pago",
            field=models.CharField(
                blank=True,
                choices=[("EF", "Efectivo"), ("TR", "Tarjeta")],
                default="EF",
                max_length=10,
                null=True,
                verbose_name="Método de Pago",
            ),
        ),
    ]
