# Generated by Django 5.0.2 on 2025-06-01 00:19

import django.db.models.deletion
import django_extensions.db.fields
import imagekit.models.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Negocios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="nombre",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre")),
                ("sector", models.CharField(max_length=50, verbose_name="Sector")),
                ("pais", models.CharField(max_length=50, verbose_name="País")),
                ("region", models.CharField(max_length=50, verbose_name="Región")),
                ("ciudad", models.CharField(max_length=50, verbose_name="Ciudad")),
                (
                    "direccion",
                    models.CharField(max_length=100, verbose_name="Dirección"),
                ),
                (
                    "telefono",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Número de teléfono"
                    ),
                ),
                (
                    "ruc",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="RUC"
                    ),
                ),
                (
                    "foto",
                    imagekit.models.fields.ProcessedImageField(
                        default="images/usuarios/negocio inicial.jpg",
                        upload_to="images",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "tipo_suscripcion",
                    models.CharField(
                        choices=[
                            ("Free", "Free"),
                            ("Basico", "Basico"),
                            ("Premium", "Premium"),
                        ],
                        default="Free",
                        max_length=20,
                        verbose_name="Tipo de suscripción",
                    ),
                ),
                (
                    "inicio_suscripcion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inicio de suscripción"
                    ),
                ),
                (
                    "fin_suscripcion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin de suscripción"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Negocio",
                "verbose_name_plural": "Negocios",
                "db_table": "Negocios",
                "ordering": ["fecha_creacion"],
                "unique_together": {("nombre", "sector", "pais", "region", "ciudad")},
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=256)),
                ("last_name", models.CharField(blank=True, max_length=256, null=True)),
                ("address", models.TextField(blank=True, max_length=256, null=True)),
                ("email", models.EmailField(blank=True, max_length=256, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("loyalty_points", models.IntegerField(default=0)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.negocios",
                        verbose_name="Negocio",
                    ),
                ),
            ],
            options={
                "db_table": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="email",
                        unique=True,
                        verbose_name="Account ID",
                    ),
                ),
                (
                    "profile_picture",
                    imagekit.models.fields.ProcessedImageField(
                        default="profile_pics/default.jpg", upload_to="profile_pics"
                    ),
                ),
                (
                    "telephone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Telephone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=150, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Last Name"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INA", "Inactivo"),
                            ("A", "Activo"),
                            ("OL", "De permiso"),
                        ],
                        default="INA",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OP", "Trabajador"),
                            ("EX", "Ejecutivo"),
                            ("AD", "Administrador"),
                        ],
                        max_length=12,
                        null=True,
                        verbose_name="Role",
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.negocios",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "db_table": "Usuarios",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "phone_number",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Phone Number"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.negocios",
                        verbose_name="Negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "db_table": "Proveedores",
            },
        ),
    ]
