# Generated by Django 5.0.2 on 2025-06-01 00:37

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="negocios",
            name="foto",
            field=imagekit.models.fields.ProcessedImageField(
                default="usuarios/negocio inicial.png", upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=imagekit.models.fields.ProcessedImageField(
                default="images/usuarios/usuario inicial.png",
                upload_to="images/usuarios",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OP", "Trabajador"),
                    ("EX", "Ejecutivo"),
                    ("AD", "Administrador"),
                ],
                default="AD",
                max_length=12,
                null=True,
                verbose_name="Role",
            ),
        ),
    ]
