# Generated by Django 5.0.2 on 2025-06-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_negocios_foto_alter_profile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="negocios",
            name="tipo_suscripcion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Free", "Free"),
                    ("Basico", "Basico"),
                    ("Premium", "Premium"),
                ],
                default="Free",
                max_length=20,
                verbose_name="Tipo de suscripción",
            ),
        ),
    ]
