# Generated by Django 5.0.2 on 2025-06-01 01:16

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_negocios_tipo_suscripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="negocios",
            name="telefono",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Número de teléfono",
            ),
        ),
    ]
