# Generated by Django 5.0.2 on 2025-05-25 23:27

import django.db.models.deletion
import imagekit.models.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Negocios",
            fields=[
                (
                    "negocio_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre")),
                ("sector", models.CharField(max_length=50, verbose_name="Sector")),
                ("pais", models.CharField(max_length=50, verbose_name="País")),
                ("region", models.CharField(max_length=50, verbose_name="Región")),
                ("ciudad", models.CharField(max_length=50, verbose_name="Ciudad")),
                (
                    "direccion",
                    models.CharField(max_length=100, verbose_name="Dirección"),
                ),
                (
                    "telefono",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Número de teléfono"
                    ),
                ),
                (
                    "ruc",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="RUC"
                    ),
                ),
                (
                    "foto",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        default="usuarios/negocio inicial.png",
                        null=True,
                        upload_to="usuarios",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "tipo_suscripcion",
                    models.CharField(
                        choices=[
                            ("Free", "Free"),
                            ("Basico", "Basico"),
                            ("Premium", "Premium"),
                        ],
                        default="Free",
                        max_length=20,
                        verbose_name="Tipo de suscripción",
                    ),
                ),
                (
                    "inicio_suscripcion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inicio de suscripción"
                    ),
                ),
                (
                    "fin_suscripcion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin de suscripción"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Negocio",
                "verbose_name_plural": "Negocios",
                "db_table": "Negocios",
                "ordering": ["fecha_creacion"],
                "unique_together": {("nombre", "sector", "pais", "region", "ciudad")},
            },
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "usuario_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=30, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=30, verbose_name="Apellido")),
                (
                    "dni",
                    models.CharField(max_length=8, unique=True, verbose_name="DNI"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=150, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        blank=True,
                        choices=[("Gerente", "Gerente"), ("Trabajador", "Trabajador")],
                        max_length=12,
                        null=True,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "telefono",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Telefono",
                    ),
                ),
                (
                    "foto",
                    imagekit.models.fields.ProcessedImageField(
                        default="usuarios/usuario inicial.jpg", upload_to="usuarios"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Inactivo", "Inactivo"),
                            ("Activo", "Activo"),
                            ("Despedido", "Despedido"),
                        ],
                        default="Activo",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "negocio_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="usuarios.negocios",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuarios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "Usuarios",
            },
        ),
    ]
