# Generated by Django 5.0.2 on 2025-06-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="negocios",
            name="numero_ventas",
        ),
        migrations.AlterField(
            model_name="negocios",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Logo de negocio"
            ),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Foto de perfil"
            ),
        ),
    ]
