# Generated by Django 5.0.2 on 2025-06-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="rol",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OP", "Trabajador"),
                    ("EX", "Ejecutivo"),
                    ("AD", "Administrador"),
                ],
                default="OP",
                max_length=13,
                verbose_name="Rol",
            ),
        ),
    ]
