# Generated by Django 5.0.2 on 2025-06-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_remove_negocios_numero_ventas_alter_negocios_foto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="negocios",
            name="numero_ventas",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Número de Ventas"
            ),
        ),
    ]
