# Generated by Django 5.2 on 2025-07-26 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_negocios_numero_ventas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="negocio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.negocios"
            ),
        ),
    ]
