# Generated by Django 5.2 on 2025-07-28 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_negocios_numero_ventas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "pago_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Pago"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto",
                    ),
                ),
                (
                    "numero_celular",
                    models.CharField(max_length=15, verbose_name="Número de Celular"),
                ),
                (
                    "comprobante_pago",
                    models.ImageField(
                        upload_to="comprobantes/", verbose_name="Comprobante de Pago"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PE", "Pendiente"),
                            ("CO", "Completado"),
                            ("EL", "Eliminado"),
                        ],
                        default="PE",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "db_table": "Pagos",
            },
        ),
    ]
