# Generated by Django 5.2 on 2025-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="codigo_autorizacion",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                verbose_name="Código de Autorización",
            ),
        ),
    ]
