# Generated by Django 5.2 on 2025-07-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_pago_codigo_autorizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="estado_codigo",
            field=models.CharField(
                choices=[("PE", "Pendiente"), ("US", "Usado")],
                default="PE",
                max_length=10,
                verbose_name="Estado del Código",
            ),
        ),
    ]
