# Generated by Django 5.0.2 on 2025-06-26 21:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Compras",
            fields=[
                (
                    "compra_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total"
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[("EF", "Efectivo"), ("TR", "Tarjeta")],
                        max_length=10,
                        verbose_name="Método de Pago",
                    ),
                ),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[("PD", "Pendiente"), ("CT", "Completado")],
                        max_length=10,
                        verbose_name="Estado de pago",
                    ),
                ),
                (
                    "estado_envio",
                    models.CharField(
                        choices=[
                            ("PT", "Pendiente"),
                            ("EV", "En envio"),
                            ("ET", "Entregado"),
                        ],
                        max_length=10,
                        verbose_name="Estado de envío",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra",
                "verbose_name_plural": "Compras",
                "db_table": "Compras",
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="DetalleCompra",
            fields=[
                (
                    "detalle_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(editable=False)),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de compra",
                "verbose_name_plural": "Detalles de compras",
                "db_table": "DetalleCompra",
                "ordering": ["detalle_id"],
            },
        ),
        migrations.CreateModel(
            name="Proveedores",
            fields=[
                (
                    "proveedor_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre")),
                (
                    "ruc",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="RUC"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Telefono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=150, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Dirección"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "db_table": "Proveedores",
                "ordering": ["negocio"],
            },
        ),
    ]
