# Generated by Django 5.0.2 on 2025-06-26 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compras", "0001_initial"),
        ("inventario", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compras",
            name="negocio",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="usuarios.negocios",
            ),
        ),
        migrations.AddField(
            model_name="detallecompra",
            name="compra",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="compras.compras",
            ),
        ),
        migrations.AddField(
            model_name="detallecompra",
            name="negocio",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="usuarios.negocios",
            ),
        ),
        migrations.AddField(
            model_name="detallecompra",
            name="producto",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventario.productos",
            ),
        ),
        migrations.AddField(
            model_name="proveedores",
            name="negocio",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="usuarios.negocios",
            ),
        ),
        migrations.AddField(
            model_name="compras",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="compras.proveedores",
                verbose_name="Proveedor",
            ),
        ),
    ]
