# Generated by Django 5.0.2 on 2025-07-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detallecompra",
            name="negocio",
        ),
    ]
